services:
  linux-env:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
      - "8085:8085"
    tty: true
    stdin_open: true
